import { Lora, Lato } from "next/font/google";
import "./globals.css";

const loraSans = Lora({
	variable: "--font-Lora-sans",
	subsets: ["latin"],
});

const latoMono = Lato({
	variable: "--font-Lato-mono",
	subsets: ["latin"],
	weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${loraSans.variable} ${latoMono.variable} relative antialiased`}
				
			>
				<div className="absolute  ">
					<div className="absolute top-0 right-0">
										<svg xmlns="http://www.w3.org/2000/svg" width="393" height="435" viewBox="0 0 393 435" fill="none">
						<g opacity="0.7" filter="url(#filter0_fn_78_409)">
							<circle cx="92.8343" cy="91.6904" r="118.987" fill="#FDF2B9"/>
						</g>
						<defs>
							<filter id="filter0_fn_78_409" x="-250.153" y="-251.297" width="685.974" height="685.975" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
								<feFlood flood-opacity="0" result="BackgroundImageFix"/>
								<feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
								<feGaussianBlur stdDeviation="112" result="effect1_foregroundBlur_78_409"/>
								<feTurbulence type="fractalNoise" baseFrequency="1 1" stitchTiles="stitch" numOctaves="3" result="noise" seed="1725"/>
								<feColorMatrix in="noise" type="luminanceToAlpha" result="alphaNoise"/>
								<feComponentTransfer in="alphaNoise" result="coloredNoise1">
									<feFuncA type="discrete" tableValues="0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 "/>
								</feComponentTransfer>
								<feComposite operator="in" in2="effect1_foregroundBlur_78_409" in="coloredNoise1" result="noise1Clipped"/>
								<feFlood flood-color="rgba(0, 0, 0, 0.25)" result="color1Flood"/>
								<feComposite operator="in" in2="noise1Clipped" in="color1Flood" result="color1"/>
								<feMerge result="effect2_noise_78_409">
									<feMergeNode in="effect1_foregroundBlur_78_409"/>
									<feMergeNode in="color1"/>
								</feMerge>
							</filter>
						</defs>
					</svg>            
					</div>


					
					<svg xmlns="http://www.w3.org/2000/svg" width="393" height="544" viewBox="0 0 393 544" fill="none">
	<g opacity="0.8" filter="url(#filter0_fn_78_408)">
		<circle cx="294.868" cy="113.127" r="206.511" fill="#76CB08"/>
	</g>
	<defs>
		<filter id="filter0_fn_78_408" x="-135.642" y="-317.384" width="861.022" height="861.022" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
			<feFlood flood-opacity="0" result="BackgroundImageFix"/>
			<feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
			<feGaussianBlur stdDeviation="112" result="effect1_foregroundBlur_78_408"/>
			<feTurbulence type="fractalNoise" baseFrequency="1 1" stitchTiles="stitch" numOctaves="3" result="noise" seed="1725"/>
			<feColorMatrix in="noise" type="luminanceToAlpha" result="alphaNoise"/>
			<feComponentTransfer in="alphaNoise" result="coloredNoise1">
				<feFuncA type="discrete" tableValues="0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 "/>
			</feComponentTransfer>
			<feComposite operator="in" in2="effect1_foregroundBlur_78_408" in="coloredNoise1" result="noise1Clipped"/>
			<feFlood flood-color="rgba(0, 0, 0, 0.25)" result="color1Flood"/>
			<feComposite operator="in" in2="noise1Clipped" in="color1Flood" result="color1"/>
			<feMerge result="effect2_noise_78_408">
				<feMergeNode in="effect1_foregroundBlur_78_408"/>
				<feMergeNode in="color1"/>
			</feMerge>
		</filter>
	</defs>
</svg>
</div>
				
				{children}
			</body>
		</html>
	);
}
